name: Developer Builds
on:
  push:
      branches: develop

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout branch
                uses: actions/checkout@v3
              - name: Cache java
                uses: satackey/action-docker-layer-caching@v0.0.11
                continue-on-error: true
              - name: Setup Java JDK
                uses: actions/setup-java@v4.2.2
                with:
                  java-version: 17
                  distribution: 'temurin'
              - name: Setup gradlew executable
                run: chmod +x ./gradlew
              - name: Build Program
                run: ./gradlew app:build
              - name: Assemble
                run: ./gradlew app:assemble
              - name: Upload build artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: build-artifacts
                    path: app/build/libs